"""Add item and user column

Revision ID: 8443e3542c60
Revises: fc6fabbe68f5
Create Date: 2023-04-30 16:08:23.749741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8443e3542c60'
down_revision = 'fc6fabbe68f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_4', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email_4'), 'users', ['email_4'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_4'), table_name='users')
    op.drop_column('users', 'email_4')
    # ### end Alembic commands ###
