"""Add item and user column2

Revision ID: f3f680501128
Revises: 8443e3542c60
Create Date: 2023-04-30 16:16:19.428779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f680501128'
down_revision = '8443e3542c60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_5', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email_5'), 'users', ['email_5'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_5'), table_name='users')
    op.drop_column('users', 'email_5')
    # ### end Alembic commands ###
