"""Add item and user column

Revision ID: fc6fabbe68f5
Revises: 2fb0f1f4fc85
Create Date: 2023-04-30 16:05:27.786815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6fabbe68f5'
down_revision = '2fb0f1f4fc85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description_4', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_description_4'), 'items', ['description_4'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_description_4'), table_name='items')
    op.drop_column('items', 'description_4')
    # ### end Alembic commands ###
